- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
  - vsphere_guest:
      vcenter_hostname: ukrdvmgvc001.dbpoc.uk
      username: wake@dbpoc.uk
      password: Start1235
      validate_certs: no
      guest: testansible
      state: powered_on
      vm_disk:
        disk1:
          size_gb: 20
          type: thin
          datastore: Test_datastore
      vm_nic:
         nic1:
          type: vmxnet3
          network: vm
          network_type: standard
      vm_hardware:
        memory_mb: 1024
        num_cpus: 1
        osid: ubuntu64Guest
        scsi: paravirtual
      esxi:
        datacenter: Synergy_Poc
        hostname: 10.0.5.98

