- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
  - vsphere_guest:
      validate_certs: no
      guest: jojjtestansible
      state: powered_on
      esxi:
        datacenter: Reading-Dev
        hostname: ukrdsesxi001.dbpoc.uk

