- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
  - vsphere_guest:
      vcenter_hostname: ukrdvmgvc001.dbpoc.uk
      username: isibor@dbpoc.uk
      password: Integration12
      validate_certs: no
      guest: jojjtestansible
      state: powered_on
      esxi:
        datacenter: Reading-Dev
        hostname: ukrdsesxi001.dbpoc.uk

